name: Build and Push Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

Jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: aransaat
          password: RRRaaa1378@
      - name: Build and push
        uses: docker/build-push-action@v2
        with: 
           context:
          push: true
          tags: aransaat/assignment6:prod
